# Generated by Django 5.2.8 on 2025-11-13 14:00

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='inside_time',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
        migrations.AddField(
            model_name='attendance',
            name='sessions',
            field=models.JSONField(default=list),
        ),
    ]
