# Generated by Django 5.2.8 on 2025-11-13 14:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0002_attendance_inside_time_attendance_sessions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='inside_time',
        ),
        migrations.RemoveField(
            model_name='attendance',
            name='sessions',
        ),
    ]
