# Generated by Django 5.2.8 on 2025-11-14 03:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_remove_attendance_inside_time_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='inside_time',
            field=models.DurationField(default=datetime.timedelta(0)),
        ),
    ]
