# Generated by Django 5.2.8 on 2025-11-14 03:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0004_attendance_inside_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='sessions',
            field=models.IntegerField(default=0),
        ),
    ]
