# Generated by Django 5.2.8 on 2025-11-14 05:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_attendance_sessions'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attendance',
            name='class_start_time',
        ),
    ]
