# Generated by Django 5.2.8 on 2025-11-14 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0006_remove_attendance_class_start_time'),
    ]

    operations = [
        migrations.AddField(
            model_name='attendance',
            name='class_start_time',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
