# Generated by Django 5.2.8 on 2025-12-23 14:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0007_attendance_class_start_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='sessions',
            field=models.IntegerField(default=1),
        ),
    ]
