# Generated by Django 5.2.8 on 2025-12-23 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0008_alter_attendance_sessions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='attendance',
            name='status',
            field=models.CharField(choices=[('Present', 'Present'), ('late', 'late'), ('Absent', 'Absent')], default='Absent', max_length=10),
        ),
    ]
